{% set org = "gdrive-org" %}
{% set name = "gdrive" %}
{% set version = "2.1.1" %}

{% set src_dir = ["src/github.com", org, name]|join("/") %}


package:
  name: gdrive
  version: {{ version }}

source:
  - url: https://github.com/{{ org }}/{{ name }}/archive/{{ version }}.tar.gz
    sha256: 9092cb356acf58f2938954784605911e146497a18681199d0c0edc65b833a672
    folder: {{ src_dir }}

  - fn: gdrive-windows-x64.exe  # [win]
    url: https://drive.google.com/uc?id=1zEaLExCMQnwftSYCF7GTONHX-lV7SlTe&export=download  # [win]
    sha256: 0fa9bf8b5319a7c3ea0f8db70441ccb4183e08033abc99835062c49250fb52fd  # [win]
    folder: bin  # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}    # [unix]
    - {{ compiler("cgo") }}  # [unix]
  host:

test:
  commands:
    - gdrive help

about:
  home: https://github.com/gdrive-org/gdrive
  license: MIT
  license_family: MIT
  license_file: {{ src_dir }}/LICENSE
  summary: Google Drive CLI Client

extra:
  recipe-maintainers:
    - jakirkham
