travis:
  secure:
    BINSTAR_TOKEN: CFY01jHFLJLtbKBXUDk0Vfp9XHd1iEZ0ljn4kFrqSYwokBKEjVJT+QuMAidinkozQRbjpln5XNpISQl/dF9hW2ikIHG4I6GW/PaNsCcjx2kuxJuxV+fqBeJ3nw8MY6I32bqVBvTuDoWS/Hj7F5hUFqp4Ahb/zV7qcLNXsehLK3hdiDbAI9vBBAcls4npEoDM4EYuqPG4SPCxivGBsKPWAOj87qomoTTUiZfA+/kOLN8wk8q7PmjKcniSOlOuDOnLEQRp6cXNtl3MCItxxXz2dEOrRonGHJp3JPUdzkYrOi5ikonFd9HMKsTRQk2t40n7r6FzL7C5g+3ICnI1TkF1xOawOAU7eZNlJ9AOUlqNEFSMOYCLun1t1xLIIygjP0sxSopFFCoCbwgIHXzaaDR99t/dHBcQR5gkT3m1DqBpKRgX3UiaHujQhRmqahXAOVNJc2PI0j3GoqRKbFrunHNmt1dBPduduzWUjqgJiAIIO2LS3yhi6+S/AiRpHxEsXvKBZLR2si0GHq/8SVNCeN9X5REIyib0sfUEsj2S/JUYBBAAlzDN1+kc0Sa1sFvYzgWZuvez8F1vsdPzBxz/oJemErwafyL7qf467RzoAZ2lqBT5Iqf9tveHrbkUlR/5JjF/7Z0wJD56Ds7C6ttNKumdhv/qo/MadT6nKsPvl7CEVV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
